### ISSUE TITLE
Perception Driven Manipulation Introduction, catkin build error 

### ISSUE THREAD

**Issue by Thompson104** [ros-industrial/industrial_training#136]
Hey all,

If you use catkin build or catkin_make for the Perception Driven Manipulation Introduction, you would find this error
`Multiple packages found with the same name "ar_track_alvar_msgs":
- ar_track_alvar/ar_track_alvar_msgs
- ar_track_alvar_msgs
`

I wonder can we bypass this problem?

**Comment by mitch1044444** [comment]
we should use rosinstall src in the workspace and then wstool update in the src folder, in case you run in to the same problem.

**Comment by jdlangs** [comment]
We did not have problems like this in the most recent training session. @Thompson104 feel free to reopen if you believe there's still a problem here.
