### ISSUE TITLE
Suggestion for tutorial Motion Planning CPP

### ISSUE THREAD

**Issue by jwhendy** [ros-industrial/industrial_training#139]
I'm going through your tutorials (which have been awesome, by the way) but translating them to `python`. I got hung up on the wording in [Motion Planning CPP](https://github.com/ros-industrial/industrial_training/wiki/Motion-Planning-CPP), Section 5:

> In the ScanNPlan class's start method below the `if (!vision_client_.call(srv))` statement , use the response from the `LocalizePart` service to create a new `move_target` variable:
```
geometry_msgs::Pose move_target = srv.response.pose;
```

Maybe I'm just slow, but for the life of me I thought this was supposed to go "below" the `if()` statement, as in "below that *line*, but inside of it." Being new to ROS and not super familiar with `C++` I spent maybe 30min trying to understand how you could define something based on what I assumed would be a failed service call (and thus how would `srv.response.pose` even exist??).

Finally I got wise and looked at the code. The file in Excercise 4.0 (not sure if this is the right one, but it contains the code) is this:
```
if (!vision_client_.call(srv))
{
  ROS_ERROR("Could not localize part");
  return;
}
ROS_INFO_STREAM("part localized: " << srv.response);
   
// Plan for robot to move to part
moveit::planning_interface::MoveGroupInterface move_group("manipulator");
geometry_msgs::Pose move_target = srv.response.pose;
move_group.setPoseTarget(move_target);
move_group.move();
```

What about saying "We'll now change our code to do something with a successful service response. After printing it with `ROS_INFO_STREAM`, create a new `move_target` variable: [tutorial continues on as usual]."

This is probably a nitpick; in hindsight, "after the statement" is obviously after the entire statement, not just after the line you quoted... Since I'm pretty darn new, I'm guessing I'm quasi in your target audience so I wanted to write the feedback based on my brain's interpretation for you! Thanks for taking a look.

**Comment by jdlangs** [comment]
@jwhendy, thanks for the feedback! I'll go ahead and close this since as you said it's more one-time feedback than an ongoing issue. Of course, you're still more than welcome to submit pull requests for any changes or improvements you'd like to see or think could be useful.
