### ISSUE TITLE
floating arm problem with descartes plugin

### ISSUE THREAD

**Issue by Vtik** [ros-industrial/industrial_training#183]
I am working on a floating arm (UR5 attached to a mobile base) and i wanted to use this plugin for creating semi constrained cartesian paths. So, I have the following configuration : 
[ WARN] [1522332092.036841775, 2753.566000000]: getTipFrame() : gripper_link
[ WARN] [1522332092.036874527, 2753.566000000]: tcp_frame : gripper_link
[ WARN] [1522332092.036893381, 2753.566000000]: getBaseFrame() : arm_base_link
[ WARN] [1522332092.036910644, 2753.566000000]: world_frame : /odom

Now, when looking inside the ur5_demo_model.cpp, there should be an identity assignement before any check on whether (tcp_frame != getTipFrame()) or (world_frame != getBaseFrame()). 
         **tool_to_tip_.frame = Affine3d::Identity();**
         **world_to_base_.frame = Affine3d::Identity();**
Otherwise, getting the poses in the arm frame will fail because of "tool_to_tip_" or "world_to_base_ (see line https://github.com/ros-industrial/industrial_training/blob/437c113ebfce69ed9551fd797c5b66e24dd3646d/exercises/Descartes_Planning_and_Execution/solution_ws/src/ur5_demo_descartes/src/ur5_robot_model.cpp#L64) are not defined previously.

Now, on the same page, it looks like getting the "arm_base_link" in the "/odom" frame is not right the way it's done at line 49, as this generates random values each time due to the setDefaultValues() called from here ( https://github.com/ros-industrial-consortium/descartes/blob/94c5c21985a7ddc1dfa192c86c9d4740508d1b2c/descartes_moveit/src/moveit_state_adapter.cpp#L90 ). So, if I am not wrong, we should figure out how to do it otherwise. Am still stuck at that point. Any ideas ? 
Thx !

**Comment by jrgnicho** [comment]
@Vtik the code in that ur5_robot_model.cpp source file was written to work well enough for the tutorial/exercise but I'd refrain from using it on a more complex project as is, especially one where the robot base isn't stationary.  The Descartes framework has made some improvements to the Robot Model interface and so I recommend looking at that repository for figuring out the proper use of that interface.
