### ISSUE TITLE
Unit testing exercise is missing code snippet

### ISSUE THREAD

**Issue by jrgnicho** [ros-industrial/industrial_training#190]
The Unit-Testing.md is missing the code snippet following the "Write a unit test to check the reference frame of the ar_pose_marker:" instruction.  After reading through the exercise is not obvious to me what should go there.  @Levi-Armstrong would you have any suggestions?

**Comment by ipa-nhg** [comment]
Solved by https://github.com/ros-industrial/industrial_training/pull/211
