### ISSUE TITLE
Instructions as Written Cause Code to Throw Error

### ISSUE THREAD

**Issue by DavidMerzJr** [ros-industrial/industrial_training#228]
In Session 5: Simple-PCL-Interface-for-Python, the command "catkin build" under Prepare New Workspace will cause an error.  The py_perception_node.cpp is filled out, but contains un-commented segments that will throw errors during build.  This is noted slightly later, but not before the page tells the user to build and experience the error.

**Comment by marip8** [comment]
This should be addressed in #245
