### ISSUE TITLE
Link to download ROS Kinetic training VM is down

### ISSUE THREAD

**Issue by j-polden** [ros-industrial/industrial_training#236]
The link to download the 'ROSI_Training_Kinetic_latest.ova' virtual machine image appears to be down. 

-------------------------------------------------------------------------------------------------------------------------------------
This site can’t be reached aeswiki.datasys.swri.edu’s server IP address could not be found.
Go to http://swri.edu/
Search Google for aes wiki datasys swri ROSI Training Kinetic latest
ERR_NAME_NOT_RESOLVED
-------------------------------------------------------------------------------------------------------------------------------------

**Comment by marip8** [comment]
@j-polden we've run into this issue a couple times recently; if you've visited the ReadTheDocs site before the link was updated (~1 month ago), then your browser probably cached the old link. Try clearing your cache/cookies for the site and try the link again.

In case that doesn't work, here is the link for the VM: https://rosi-images.datasys.swri.edu/

**Comment by DigitalChimera141** [comment]
The issue still persists and not working even with a vpn
Though the swri.org website works!
