### ISSUE TITLE
 qt plugin ros installer is broken

### ISSUE THREAD

**Issue by olmerg** [ros-industrial/industrial_training#252]
the link to install QT from [the script](https://github.com/ros-industrial/industrial_training/blob/melodic/gh_pages/_downloads/ros-melodic-industrial-training.sh) is broken in bionic and in xenail.

From the page [How to Install (Users)](https://qtcreator-ros.datasys.swri.edu/downloads/installers/bionic/qtcreator-ros-bionic-latest-online-installer.run) the links are:

[for Xenail](https://qtcreator-ros.datasys.swri.edu/downloads/installers/xenial/qtcreator-ros-xenial-latest-online-installer.run)
[for bionic](https://qtcreator-ros.datasys.swri.edu/downloads/installers/bionic/qtcreator-ros-bionic-latest-online-installer.run)

**Comment by dejaniraai** [comment]
#283 Pull request for review to fix this issue
