### ISSUE TITLE
[Demo 1] Missing dependencies

### ISSUE THREAD

**Issue by jdlangs** [ros-industrial/industrial_training#265]
To successfully compile the template workspace, additional dependencies have to be installed (i.e., cloned into the workspace):

- [manipulation_msgs](https://github.com/ros-interactive-manipulation/manipulation_msgs)
- [household_objects_database_msgs](https://github.com/ros-interactive-manipulation/household_objects_database_msgs)
- ur_msgs

Hopefully the UR repository will soon be released for melodic, removing that from the list. The first two, however, are explicitly described as deprecated and so it would probably be ideal to remove them from the training material entirely.

**Comment by dejaniraai** [comment]
#274 Created pull request to change dependencies to the updated moveit_msgs package that  is installed by default, instead of the deprecated manipulation_msgs
