### ISSUE TITLE
[Demo 1] Eigen::Transform incompatibilty

### ISSUE THREAD

**Issue by jdlangs** [ros-industrial/industrial_training#266]
Due to an API change in melodic, [this line](https://github.com/ros-industrial/industrial_training/blob/245438735fb353d8e027378622278bb791d85e9b/exercises/Perception-Driven_Manipulation/template_ws/src/collision_avoidance_pick_and_place/src/tasks/set_attached_object.cpp#L34) doesn't compile. Changing `pose_array` to an `Isometry3d` vector resolved the problems.

**Comment by jdlangs** [comment]
It may also be a good idea to do a more thorough change of `Affine3d` to `Isometry3d` while fixing this.

**Comment by ngwk1** [comment]
#277. Changed `Affine3d` to `Isometry3d` to skip compilation error. Please review the changes.

**Comment by jdlangs** [comment]
Closed by #277.
