### ISSUE TITLE
[Demo 1] hw_interface argument to ur_arm_transmission xacro macro

### ISSUE THREAD

**Issue by jdlangs** [ros-industrial/industrial_training#267]
The current UR5 description package requires a `hw_interface` argument for the `ur_arm_transmission` xacro macro which the copy of `ur5.urdf.xacro` in the training material [is missing](https://github.com/ros-industrial/industrial_training/blob/245438735fb353d8e027378622278bb791d85e9b/exercises/Perception-Driven_Manipulation/template_ws/src/robot_config/urdf/ur5.urdf.xacro#L313). After a brief comparison I didn't see any notable difference between this file and the one from `ur_description` so probably this file should just be deleted and the UR5 macro from the official package should be used instead.

**Comment by ngwk1** [comment]
#279 Added additional parameters `hw_interface` to overcome compilation error. Please review the changes.

**Comment by marip8** [comment]
Closing; addressed by #315
