### ISSUE TITLE
[Demo 2] Reference to header files that do not exist in Melodic

### ISSUE THREAD

**Issue by dejaniraai** [ros-industrial/industrial_training#278]
Reference to headers:
`#include <moveit/kdl_kinematics_plugin/chainiksolver_pos_nr_jl_mimic.hpp> 
#include <moveit/kdl_kinematics_plugin/chainiksolver_vel_pinv_mimic.hpp>`

This was corrected for exercise 4.1 (Descartes), but it is present in the Demo2 template and solution folders.

**Comment by Derrickakq** [comment]
#281 Fixed header files by commenting them out as it does not exist on ros-melodic

**Comment by jrgnicho** [comment]
fixed by #281

**Comment by JeremyZoss** [comment]
Fixed in #281, which is now merged.  Closing this issue.

**Comment by marip8** [comment]
This issue also exists in Exercise 5.0; will make a PR soon to fix this

**Comment by gavanderhoorn** [comment]
Tracking in #292.

**Comment by gavanderhoorn** [comment]
@marip8: I'm closing this again as the problem with ex5 is tracked in #292 and it's best not to 'append' problems to issues already closed.
