### ISSUE TITLE
Configure repository to require PR reviews

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/industrial_training#282]
Just noticed this repository does not enfore PR reviews before merging.

I suggest we setup a policy and -- if available -- also require CI to pass.

**Comment by dejaniraai** [comment]
Yes, this is a good idea. Is it usually the maintainer who decides this, or can any administrator add these policies?

**Comment by gavanderhoorn** [comment]
It's up to the maintainers typically.

I'll setup a temporary policy and let @ros-industrial/industrial-training-push decide later.

**Comment by gavanderhoorn** [comment]
Both `kinetic` and `melodic` have a temporary policy setup.

**Comment by marip8** [comment]
@gavanderhoorn I just updated the `kinetic` and `melodic` branches to require passing CI before merge. I'm not sure it's necessary to update earlier distribution branches in a similar way. It seems like this is enough to close this issue. Any thoughts?

**Comment by gavanderhoorn** [comment]
I believe this is OK. Indigo and earlier are deprecated, so the current configuration would seem sufficient.
