### ISSUE TITLE
[Perception-Driven_Manipulation] Cannot launch node mongo_wrapper_ros.py

### ISSUE THREAD

**Issue by ngwk1** [ros-industrial/industrial_training#284]
Error occur when attempting to launch `default_warehouse_db.launch` from `ur5_pick_and_place.launch` from the `collision_avoidance_pick_and_place` package. 

**Summary**
ERROR: cannot launch node of type [warehouse_ros/mongo_wrapper_ros.py]: can't locate node [mongo_wrapper_ros.py] in package [warehouse_ros]

**Comment by ngwk1** [comment]
#285 Removed the line which included the launch file `default_warehouse_db.launch`. The file is not required to run the demo.

**Comment by jdlangs** [comment]
Closed by #285
