### ISSUE TITLE
(Exercise 5.3) Missing Instruction in text

### ISSUE THREAD

**Issue by gtan039** [ros-industrial/industrial_training#286]
Build error occurs when perception_msgs dependency was added in the CMakeLists 

Suggestion to run the following package to transform the reference frame of the point cloud to the world frame

rosrun tf2_ros static_transform_publisher 0 0 0 0 0 0 0 world_frame kinect_link

**Comment by dejaniraai** [comment]
#287 Pull request  created for review.
