### ISSUE TITLE
Ex5.0: chainiksolver_pos_nr_jl_mimic.hpp does not exist any more

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/industrial_training#292]
Similar to #278, but in exercise 5.0.

**Comment by gavanderhoorn** [comment]
@marip8

**Comment by gavanderhoorn** [comment]
@marip8: was this fixed in a PR (#294 perhaps)? If so, could you perhaps add a final comment linking to that PR?

**Comment by marip8** [comment]
@gavanderhoorn yes, this issue was addressed by #294.
