### ISSUE TITLE
Any plan for later versions

### ISSUE THREAD

**Issue by JaehyunShim** [ros-industrial/industrial_training#330]
As the title says, I wonder if there are going to be updates for the noetic and ROS2 versions for industrial_training.

**Comment by robinsonmm** [comment]
There are ROS2 exercises.

We will be making a bit update in line for the Americas Feb 2021, which
will include Noetic and Foxy ports.

https://industrial-training-master.readthedocs.io/en/latest/index.html

**Comment by JaehyunShim** [comment]
Thank you.
