### ISSUE TITLE
Link is leading to default ubuntu page

### ISSUE THREAD

**Issue by Nir0n** [ros-industrial/industrial_training#411]
https://github.com/ros-industrial/industrial_training/blob/1f327dee1055d50abc9a0f7fd88254c124d97190/gh_pages/_source/setup/PC-Setup---ROS.md?plain=1#L8

Greetings. The required image was deleted. Can you update the link?
Thank you!

**Comment by reidchristopher** [comment]
Thanks for pointing this out. I'll look into getting this fixed
