### ISSUE TITLE
indigo build errors

### ISSUE THREAD

**Issue by jrgnicho** [ros-industrial/industrial_training#46]
The ccny_vision packages under the supplements directory will not build under ros-indigo.  Also, industrial_core is not a available as a debian release so it will have to be copied to the supplements or be manually installed in some way.

**Comment by gavanderhoorn** [comment]
On 8-4-2015 20:44, Jorge Nicho wrote:
> The ccny_vision packages under the supplements directory will not build under ros-indigo.  Also, industrial_core is not a available as a debian release so it will have to be copied to the supplements or be manually installed in some way.  

fyi: industrial_core was recently released into Indigo, but the pkg
mirrors have not yet been synced completely.

Switching to ros-shadow-fixed should allow you to install it using apt-get.

**Comment by shaun-edwards** [comment]
It's not installable under indigo.

**Comment by shaun-edwards** [comment]
I mean it is NOW installable under indigo.

**Comment by gavanderhoorn** [comment]
On 8-4-2015 22:22, Shaun Edwards wrote:
> I mean it is NOW installable under indigo.

you got me confused for a minute there :)

**Comment by jrgnicho** [comment]
I just built PR #50 successfully with the debian install of industrial_core.

**Comment by gomezc** [comment]
Merged the branch for this issue and confirmed successful build with changes to ccny_vision.
